# DATA SCIENCE SESSIONS VOL. 3
### A Foundational Python Data Science Course
## TaskList 09: Probability 2.

[&larr; Back to course webpage](https://datakolektiv.com/)

Feedback should be send to [goran.milovanovic@datakolektiv.com](mailto:goran.milovanovic@datakolektiv.com). 

These notebooks accompany the DATA SCIENCE SESSIONS VOL. 3 :: A Foundational Python Data Science Course.

![](../img/IntroRDataScience_NonTech-1.jpg)

### Lecturers

[Goran S. Milovanović, PhD, DataKolektiv, Chief Scientist & Owner](https://www.linkedin.com/in/gmilovanovic/)

[Aleksandar Cvetković, PhD, DataKolektiv, Consultant](https://www.linkedin.com/in/alegzndr/)

[Ilija Lazarević, MA, DataKolektiv, Consultant](https://www.linkedin.com/in/ilijalazarevic/)

![](../img/DK_Logo_100.png)

***

### Intro

In this tasklist we will deal with the basics of Probability Theory as presented in Session 08 and 09. 
This tasklist is meant as a refresher of what was discussed in the sessions. It is not meant to improve your Python coding skills except for very basic things in Numpy and Scipy and all in relation to Probability Theory alone. 

**00.** Use Scipy to create 1,000 random numbers from the Normal distribution with $\mu=5$ and $\sigma=2$. Then compute the mean from the sample that you have generated, and the standard deviation - do not forget about the $N-1$ correction!

In [2]:
### Setup
import numpy as np
from scipy.stats import norm

norm_sample = norm.rvs(size=1000, loc=5, scale=2)
norm_sample

array([ 5.32970064,  3.6831523 ,  5.00846559,  4.21936193, -0.35701222,
        7.14836509,  2.72837236,  4.53061886,  4.48332368,  8.73794009,
        6.26633046,  4.11161296,  5.85362486,  1.90942575,  2.0378798 ,
        7.09387807,  2.4939736 ,  7.94086442,  7.81526158,  7.62163383,
        8.55746554,  6.48715526,  7.11093467,  4.01081828,  6.50588411,
        5.07811953,  3.77411995,  2.48670791,  6.77590579,  4.89874184,
        1.77770865,  1.22051523,  4.31866911,  5.00195843,  4.21055234,
        3.09253636,  3.63551372,  4.30828646,  3.7756492 ,  4.29083089,
        7.285184  ,  4.17395342,  4.76935954,  2.25873125,  4.08170329,
        5.24463971,  4.75185635,  4.71035317,  3.57462432,  8.13447618,
        4.75946881,  4.31638198,  6.50936125,  3.04294549,  5.38133339,
        3.56920427,  4.88631616,  5.41922865,  4.94996137,  5.68898092,
        5.66885516,  7.59022861,  5.52348549,  4.21309234,  7.99800417,
        3.60912052,  5.95105824,  2.19638413,  8.17662305,  6.03

In [5]:
m = norm_sample.mean()
print(f'The mean is {m}.')

The mean is 4.982427162009774.


In [6]:
s = norm_sample.std(ddof=1)
print(f'The standard deviation is {s}.')

The standard deviation is 1.9616393797221683.


**01.** Use Numpy to standardize all observations in your sample from $\mathcal{N}(5, 2)$. Compute the mean and the standard deviation of the standardized observations.

In [7]:
z_norm_sample = (norm_sample-m)/s
z_norm_sample

array([ 1.77032271e-01, -6.62341343e-01,  1.32738119e-02, -3.88993635e-01,
       -2.72192710e+00,  1.10414684e+00, -1.14906686e+00, -2.30321795e-01,
       -2.54431821e-01,  1.91447672e+00,  6.54505263e-01, -4.43921655e-01,
        4.44117152e-01, -1.56654758e+00, -1.50106457e+00,  1.07637057e+00,
       -1.26855812e+00,  1.50814532e+00,  1.44411580e+00,  1.34540869e+00,
        1.82247482e+00,  7.67076822e-01,  1.08506565e+00, -4.95304533e-01,
        7.76624372e-01,  4.87818323e-02, -6.15968064e-01, -1.27226201e+00,
        9.14275401e-01, -4.26609091e-02, -1.63369401e+00, -1.91773879e+00,
       -3.38369047e-01,  9.95660562e-03, -3.93484569e-01, -9.63424174e-01,
       -6.86626428e-01, -3.43661891e-01, -6.15188485e-01, -3.52560351e-01,
        1.17389407e+00, -4.12141878e-01, -1.08617122e-01, -1.38847942e+00,
       -4.59168937e-01,  1.33670107e-01, -1.17539857e-01, -1.38697253e-01,
       -7.17666489e-01,  1.60684428e+00, -1.13659197e-01, -3.39534980e-01,
        7.78396937e-01, -

In [8]:
z_norm_sample.mean()

-1.2612133559741777e-16

In [9]:
z_norm_sample.std(ddof=1)

1.0

**02.** Recall the formula for the Expected Value (EV) of a Binomial Random Variable (RV). Use the formula to compute the mean of a Binomial RV with $n=1000$ and $p=.23$. Better: write a Python function to compute the EV of a Binomial RV and apply the function to a Binomial with $n=1000$ and $p=.23$.

In [11]:
def binomial_ev(p, n):
    return n*p
binomial_ev(.23, 1000)

230.0

**03.** Recall the formula for the variance of a Binomial Random Variable (RV). Use the formula to compute the variance of a Binomial RV with $n=3000$ and $p=.71$. Better: write a Python function to compute the variance of a Binomial RV and apply the function to a Binomial with $n=3000$ and $p=.71$.

In [12]:
def binomial_var(p, n):
    return n*p*(1-p)
binomial_var(.71, 3000)

617.7

**04.** A friend of mine is running a customer support centre. They receive a call every five minutes on the average. What is the probability that they will **not** receive a call in no more ten minutes? **N.B. Tricky**.

In [16]:
from scipy.stats import expon
p_ten_not = 1 - expon.cdf(x=9, scale = 5)
print(f'The probability of not obtaining a call in no more than ten minutes is {p_ten_not}.')

The probability of not obtaining a call in no more than ten minutes is 0.16529888822158656.


**05.** And what What is the probability that they will receive a call in no more ten minutes?

In [17]:
p_ten = expon.cdf(x=10, scale = 5)
print(f'The probability of obtaining a call in no more than ten minutes is {p_ten}.')

The probability of obtaining a call in no more than ten minutes is 0.8646647167633873.


**06.** Draw a sample of 10000 uniformly distributed random numbers from the Continous Uniform Distribution on [0,1]. Recall the Normal Quantile function: use it to generate 10000 normally distributed random numbers with $\mu=5$ and $\sigma=2$ from the uniformly distributed ones that you have generated. Compute the mean and the standard deviation of the resulting Normal random numbers.

In [30]:
from scipy.stats import uniform
unif_rvs = uniform.rvs(size = 10000)
unif_rvs

array([0.25210907, 0.69284357, 0.22767879, ..., 0.05086381, 0.81137081,
       0.24873773])

In [31]:
norm_rvs = norm.ppf(q=unif_rvs, loc=5, scale=2)
norm_rvs_mean = norm_rvs.mean()
norm_rvs_std = norm_rvs.std(ddof=1)
print(f'The mean is {norm_rvs_mean}.')
print(f'The mean is {norm_rvs_std}.')

The mean is 5.000639837430205.
The mean is 1.9832337702964835.


***

DataKolektiv, 2022/23.

[hello@datakolektiv.com](mailto:goran.milovanovic@datakolektiv.com)

![](../img/DK_Logo_100.png)

<font size=1>License: [GPLv3](https://www.gnu.org/licenses/gpl-3.0.txt) This Notebook is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This Notebook is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this Notebook. If not, see http://www.gnu.org/licenses/.</font>